@startuml
title Activity Diagram -  הגופים N בעיית

(*) --> "בחירת פעולה"

if "איזו פעולה נבחרה?" then
  -->[הוספה] "הזנת נתוני גוף"
  --> "בדיקת תקינות קלט"

  if "הקלט תקין?" then
    -->[כן] "הוספת גוף לרשימת הגופים"
    --> "ניקוי טופס הקלט"
    --> (*)
  else
    -->[לא] "הצגת הודעת שגיאה"
    --> (*)
  endif

else
  if "איזו פעולה נבחרה?" then
    -->[עדכון] "בחירת גוף קיים"
    --> "האם נבחר גוף קיים?"

    if "נבחר גוף?" then
      -->[כן] "הזנת נתוני גוף"
      --> "בדיקת תקינות קלט"

      if "הקלט תקין?" then
        -->[כן] "עדכון גוף קיים"
        --> (*)
      else
        -->[לא] "הצגת הודעת שגיאה"
        --> (*)
      endif

    else
      -->[לא] "הצגת הודעת שגיאה"
      --> (*)
    endif

  else
    if "איזו פעולה נבחרה?" then
      -->[מחיקה] "בחירת גוף"
      --> "מחיקת גוף מרשימת הגופים"
      --> (*)

    else
      if "איזו פעולה נבחרה?" then
        -->[ניקוי] "ניקוי טופס הקלט"
        --> (*)

      else
        -->[הרצה] "האם יש גופים ברשימה?"

        if "יש גופים?" then
          -->[כן] "ביצוע חישוב נומרי"
          --> "חישוב כוחות כבידה בין הגופים"
          --> "עדכון מהירויות ומיקום"
          --> "עדכון התצוגה הגרפית"
          --> (*)
        else
          -->[לא] "הצגת הודעת שגיאה"
          --> (*)
        endif
      endif
    endif
  endif
endif

@enduml